### ISSUE TITLE
US#1 Yo como {product owner} quiero {un programa en Python} para {el análisis estadístico de desastres naturales}

### ISSUE THREAD

**Issue by Gona79** [ispc-programador2022/UYVV4#1]
- [x] US#1TK#1 Armar el equipo, po, sm, team
- [x] US#1TK#2 Crear repositorio, con proyecto en github
- [x] US#1TK#3 Crear Kanban en Trello
- [x] US#1TK#4 Definir estructura del proyecto (Dev y Documentacion) para un programa en Python
- [x] US#1TK#5 Definir la pagina web del scrapping de datos

**Comment by Mar-Urzag** [comment]
Como Product Owner considero necesario el desarrollo de  un programa en Python para  la recoleccion y analisis de datos referido a Desastres Naturales, ya que en la actualidad los problemas ambientales agudos están asociados al deterioro de los suelos, la degradación de las pasturas, la destrucción de los bosques y la pérdida de la biodiversidad genética y ecosistémica.
Los resultados obtenidos en la App  permitirá a los usuario  visualizar de forma efectiva y simplificada la  información.

**Comment by Mar-Urzag** [comment]
Buen trabajo equipo @clau-yon @Gona79 @Mar-Urzag @marianovila .
